QA = {
    "hotel-pricerange": {
        "description1": "what is the price budget for the hotel?",
        "description2": "what is the cost of the hotel?",
        "values": ["cheap", "moderate", "expensive", "dontcare", "not mentioned"],
    },
    "hotel-type": {
        "description1": "what is the type of hotel?",
        "description2": "what is the hotel type?",
        "values": ["hotel", "guesthouse", "dontcare", "not mentioned"],
    },
    "hotel-parking": {
        "description1": "does the hotel have a parking lot?",
        "description2": "does the hotel have a parking lot?",
        "values": ["yes", "no", "free", "dontcare", "not mentioned"],
    },
    "hotel-stay": {
        "description1": "how long did user book the hotel?",
        "description2": "how long did user book the hotel?",
    },
    "hotel-day": {
        "description1": "what day did user book the hotel?",
        "description2": "what day will user stay at the hotel?",
        "values": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "dontcare",
            "not mentioned",
        ],
    },
    "hotel-people": {
        "description1": "what is the number of people for the hotel booking?",
        "description2": "how many people will stay at the hotel?",
    },
    "hotel-area": {
        "description1": "where is the area of the hotel?",
        "description2": "where is the area of the hotel?",
    },
    "hotel-stars": {
        "description1": "what is the star rating of the hotel?",
        "description2": "what is the star rating of the hotel?",
        "values": ["0", "1", "2", "3", "4", "5", "dontcare", "not mentioned"],
    },
    "hotel-internet": {
        "description1": "does the user want a hotel with internet access?",
        "description2": "does the user want a hotel with internet access?(multiple choice)",
        "values": ["yes", "no", "dontcare", "not mentioned"],
    },
    "train-destination": {
        "description1": "where is destination of train?",
        "description2": "where is the train's destination?",
    },
    "train-day": {
        "description1": "what day did user book the train?",
        "description2": "what day did user book the train?",
        "values": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "dontcare",
            "not mentioned",
        ],
    },
    "train-departure": {
        "description1": "where is the departure location of train?",
        "description2": "where is the departure location of train?",
    },
    "train-arrive": {
        "description1": "when is the train arriving?",
        "description2": "when is the train arriving?",
    },
    "train-people": {
        "description1": "what is the number of people for the train booking?",
        "description2": "what is the number of people for the train booking?",
    },
    "train-leave": {
        "description1": "when is the train leaving?",
        "description2": "when is the train leaving?",
    },
    "attraction-area": {
        "description1": "what is the area of the attraction?",
        "description2": "where is the attraction?",
    },
    "restaurant-food": {
        "description1": "what kind of food do restaurants serve?",
        "description2": "what kind of food do restaurants serve?",
    },
    "restaurant-pricerange": {
        "description1": "what is the price budget for the restaurant?",
        "description2": "what is the price budget for the restaurant?",
        "values": ["expensive", "cheap", "moderate", "dontcare", "not mentioned"],
    },
    "restaurant-area": {
        "description1": "where is the area of the restaurant?",
        "description2": "Where is the restaurant located?",
    },
    "attraction-name": {
        "description1": "what is attraction name?",
        "description2": "what is attraction name?",
    },
    "restaurant-name": {
        "description1": "what is restaurant name?",
        "description2": "what is the name of the restaurant?",
    },
    "attraction-type": {
        "description1": "what is the type of attraction?",
        "description2": "what are the types of attraction?",
    },
    "hospital-department": {
        "description1": "what is department of hospital",
        "description2": "what is department of hospital",
    },
    "hotel-name": {
        "description1": "what is hotel name?",
        "description2": "what name hotel do users want to stay in?",
    },
    "taxi-leave": {
        "description1": "when is the taxi leaving?",
        "description2": "What time does the taxi leave?",
    },
    "taxi-destination": {
        "description1": "where is destination of taxi?",
        "description2": "where is destination of taxi?",
    },
    "taxi-departure": {
        "description1": "where is the departure location of taxi?",
        "description2": "where is the taxi's departure point?",
    },
    "restaurant-time": {
        "description1": "when is the book time of restaurant?",
        "description2": "when is the book time of restaurant?",
    },
    "restaurant-day": {
        "description1": "What day did user book the restaurant?",
        "description2": "when is the restaurant reservation day?",
        "values": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "dontcare",
            "not mentioned",
        ],
    },
    "restaurant-people": {
        "description1": "what is the number of people for the restaurant booking?",
        "description2": "how many people make a reservation for a restaurant?",
    },
    "taxi-arrive": {
        "description1": "when is the taxi arriving?",
        "description2": "when will the taxi arrive?",
    },
    "bus-departure": {
        "description1": "where is the departure location of bus?",
        "description2": "where is the departure location of bus?(extract)",
    },
    "bus-destination": {
        "description1": "where is destination of bus?",
        "description2": "where is destination of bus?(extract)",
    },
    "bus-leave": {
        "description1": "when is the bus leaving?",
        "description2": "when is the bus leaving?",
    },
    "bus-day": {
        "description1": "what day did user book the bus?",
        "description2": "what day did user book the bus?(multiple-choice)",
        "values": [
            "monday",
            "tuesday",
            "wednesday",
            "thursday",
            "friday",
            "saturday",
            "sunday",
            "dontcare",
            "not mentioned",
        ],
    },
    "multichoice-domain": [
        "hotel-pricerange",
        "hotel-type",
        "hotel-parking",
        "hotel-day",
        "hotel-stars",
        "hotel-internet",
        "train-day",
        "restaurant-pricerange",
        "restaurant-day",
    ],
    "extract-domain": [
        "attraction-type",
        "hotel-people",
        "hotel-area",
        "restaurant-area",
        "hotel-stay",
        "train-destination",
        "train-departure",
        "train-arrive",
        "train-people",
        "train-leave",
        "attraction-area",
        "restaurant-food",
        "attraction-name",
        "restaurant-name",
        "restaurant-people",
        "taxi-arrive",
        "hotel-name",
        "taxi-leave",
        "taxi-destination",
        "taxi-departure",
        "restaurant-time",
    ],
    "all_domain": [
        "attraction-type",
        "attraction-name",
        "attraction-area",
        "hotel-pricerange",
        "hotel-type",
        "hotel-parking",
        "hotel-day",
        "hotel-stars",
        "hotel-internet",
        "hotel-name",
        "hotel-people",
        "hotel-area",
        "hotel-stay",
        "restaurant-time",
        "restaurant-pricerange",
        "restaurant-day",
        "restaurant-area",
        "restaurant-food",
        "restaurant-name",
        "restaurant-people",
        "train-destination",
        "train-departure",
        "train-arrive",
        "train-day",
        "train-people",
        "train-leave",
        "taxi-leave",
        "taxi-destination",
        "taxi-arrive",
        "taxi-departure",
    ],
    "bigger_domain": ["train", "taxi", "hotel", "restaurant", "attraction"],
    "NOT_MENTIONED": "not mentioned",
}
